function dy = My_DoublePendulum(t,in2)
%My_DoublePendulum
%    DY = My_DoublePendulum(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    26-Nov-2021 10:25:56

%This function was created automatically from funcbund.createMyDoublePendulum
%accepts column vectors and returns column vectors
%t is entered to allow function to be called in ODEsolvers even though its not used
dth1 = in2(3,:);
dth2 = in2(4,:);
th1 = in2(1,:);
th2 = in2(2,:);
t2 = sin(th1);
t3 = sin(th2);
t4 = dth1.^2;
t5 = dth2.^2;
t6 = -th2;
t7 = -t3;
t8 = t6+th1;
t9 = cos(t8);
t10 = sin(t8);
t11 = t9.^2;
t12 = t4.*t10;
t14 = (t5.*t10)./3.0;
t13 = t11./3.0;
t16 = t2+t14;
t15 = t13-1.0;
t18 = t9.*t16;
t17 = 1.0./t15;
t19 = t7+t12+t18;
dy = [dth1;dth2;-t16+(t9.*t17.*t19)./3.0;-t17.*t19];
